#!/usr/bin/env bash
# 100-redirect_http_to_https

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    mode http
    option forwardfor
    reqadd X-Forwarded-Proto:\ http
    acl is_holberton hdr_end(host) -i www.victorkayke.tech
    redirect scheme https code 301 if !{ ssl_fc } is_holberton

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.victorkayke.tech/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    acl is_holberton hdr_end(host) -i www.victorkayke.tech
    use_backend holberton_backend if is_holberton

backend holberton_backend
    balance roundrobin
    server web-server-1 100.25.168.39:80 check
    server web-server-2 54.90.2.249:80 check
