#!/bin/bash

# Check if correct number of arguments is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign command-line arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer the file using scp to the user home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~

echo "File transfer completed successfully."
