#!/usr/bin/env bash
if [ -e /etc/nginx/sites-enabled/default ] then rm /etc/nginx/sites-enabled/default fi
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -t; nginx -s reload
service nginx status | grep -q "not running" && echo "nginx is not running"
