#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo systemctl start nginx
