#!/usr/bin/env bash
# A Bash script that runs the whoami command on the first argument passed to it.
# Assuming the first command passed to the script is a user registered on the system.
sudo -u "$1" whoami
