#!/usr/bin/env bash

# Bash script to connect to the server using SSH with the private key ~/.ssh/school and the user ubuntu

# Server details
server_ip="100.25.168.39"
server_user="ubuntu"
private_key_path="C:\Users\Administrator\.ssh"

# SSH connection using private key
ssh -i ~/.ssh/school $server_user@$server_ip
